//
//  UIColor+KinStyle.swift
//
//  Generated by Zeplin on 3/8/18.
//  Copyright (c) 2018 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var kinWhite: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinLightBlueGrey: UIColor { 
		return UIColor(red: 215.0 / 255.0, green: 220.0 / 255.0, blue: 233.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinBrightSkyBlue: UIColor { 
		return UIColor(red: 8.0 / 255.0, green: 198.0 / 255.0, blue: 241.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinBrightBlue: UIColor { 
		return UIColor(red: 2.0 / 255.0, green: 98.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinBlueGrey: UIColor { 
		return UIColor(red: 92.0 / 255.0, green: 103.0 / 255.0, blue: 134.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinBlueGreyTwo: UIColor { 
		return UIColor(red: 120.0 / 255.0, green: 132.0 / 255.0, blue: 165.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinAzure: UIColor { 
		return UIColor(red: 5.0 / 255.0, green: 150.0 / 255.0, blue: 248.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinBrightBlueTwo: UIColor { 
		return UIColor(red: 3.0 / 255.0, green: 109.0 / 255.0, blue: 254.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinCoralPink: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 94.0 / 255.0, blue: 119.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinWatermelon: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 75.0 / 255.0, blue: 103.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinMango: UIColor { 
		return UIColor(red: 255.0 / 255.0, green: 134.0 / 255.0, blue: 46.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinDeepSkyBlue: UIColor { 
		return UIColor(red: 4.0 / 255.0, green: 124.0 / 255.0, blue: 252.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinAzureTwo: UIColor { 
		return UIColor(red: 7.0 / 255.0, green: 181.0 / 255.0, blue: 243.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinDeepSkyBlueTwo: UIColor { 
		return UIColor(red: 4.0 / 255.0, green: 126.0 / 255.0, blue: 252.0 / 255.0, alpha: 1.0)
	}

	@nonobjc class var kinLightAqua: UIColor { 
		return UIColor(red: 130.0 / 255.0, green: 255.0 / 255.0, blue: 238.0 / 255.0, alpha: 1.0)
	}
}
