//
// EarnSubmission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class EarnSubmission: JSONEncodable {

    public var recipientAddress: String?
    public var completedForm: Any?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["recipient_address"] = self.recipientAddress
        nillableDictionary["completed_form"] = self.completedForm

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

