//
// Limits.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Limits: JSONEncodable {

    public var supply: Int32?
    public var expiration: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["supply"] = self.supply?.encodeToJSON()
        nillableDictionary["expiration"] = self.expiration

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

