//
// MultiChoicePollAnswer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class MultiChoicePollAnswer: JSONEncodable {

    public enum ContentType: String { 
        case multiChoicePollAnswer = "MultiChoicePollAnswer"
    }
    public var contentType: ContentType?
    public var answers: [Int32]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["content_type"] = self.contentType?.rawValue
        nillableDictionary["answers"] = self.answers?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

