//
// Offer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Offer: JSONEncodable {

    public enum OfferType: String { 
        case earn = "earn"
        case spend = "spend"
    }
    public var id: String?
    public var title: String?
    public var description: String?
    public var image: String?
    public var limits: Limits?
    public var amount: Int32?
    public var content: Any?
    public var offerType: OfferType?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["title"] = self.title
        nillableDictionary["description"] = self.description
        nillableDictionary["image"] = self.image
        nillableDictionary["limits"] = self.limits?.encodeToJSON()
        nillableDictionary["amount"] = self.amount?.encodeToJSON()
        nillableDictionary["content"] = self.content
        nillableDictionary["offer_type"] = self.offerType?.rawValue

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

