//
// SliderPollAnswer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SliderPollAnswer: JSONEncodable {

    public enum ContentType: String { 
        case sliderPollAnswer = "SliderPollAnswer"
    }
    public var contentType: ContentType?
    public var value: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["content_type"] = self.contentType?.rawValue
        nillableDictionary["value"] = self.value

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

