//
// SliderPoll.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SliderPoll: JSONEncodable {

    public enum ContentType: String { 
        case sliderPoll = "SliderPoll"
    }
    public var contentType: ContentType?
    public var min: Int32?
    public var max: Int32?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["content_type"] = self.contentType?.rawValue
        nillableDictionary["min"] = self.min?.encodeToJSON()
        nillableDictionary["max"] = self.max?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

