//
// SpendResultAsset.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SpendResultAsset: JSONEncodable {

    public enum AssetType: String { 
        case code = "coupon_code"
    }
    public var couponCode: String?
    public var assetType: AssetType?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["coupon_code"] = self.couponCode
        nillableDictionary["asset_type"] = self.assetType?.rawValue

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

