//
// SpendSubmission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SpendSubmission: JSONEncodable {

    public var transactionId: String?
    public var senderAddress: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["transaction_id"] = self.transactionId
        nillableDictionary["sender_address"] = self.senderAddress

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

