//
// SpendResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SpendResult: JSONEncodable {

    public enum OfferType: String { 
        case spendResult = "SpendResult"
    }
    public var offerType: OfferType?
    public var asset: SpendResultAsset?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["offer_type"] = self.offerType?.rawValue
        nillableDictionary["asset"] = self.asset?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

