//
// Submission.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Submission: JSONEncodable {

    public enum OfferType: String { 
        case earnSubmission = "EarnSubmission"
        case spendSubmission = "SpendSubmission"
    }
    public var transactionId: String?
    public var senderAddress: String?
    public var recipientAddress: String?
    public var completedForm: Any?
    public var offerType: OfferType?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["transaction_id"] = self.transactionId
        nillableDictionary["sender_address"] = self.senderAddress
        nillableDictionary["recipient_address"] = self.recipientAddress
        nillableDictionary["completed_form"] = self.completedForm
        nillableDictionary["offer_type"] = self.offerType?.rawValue

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

