//
// TransactionHistoryItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TransactionHistoryItem: JSONEncodable {

    public enum Status: String { 
        case pending = "pending"
        case completed = "completed"
        case failed = "failed"
    }
    public var status: Status?
    public var orderId: String?
    public var order: SubmissionResult?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["status"] = self.status?.rawValue
        nillableDictionary["order_id"] = self.orderId
        nillableDictionary["order"] = self.order?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

